package com.task.Vodafone.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name="roles")//Specifies the name of the database table to be used for mapping this entity.
public class Role
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)/*auto increment and unique key value
    annotation from JPA and specifies that the primary key values are automatically generated by
    the database using an identity column.
    */
    private Long id;

    @Column(nullable=false, unique=true)
    private String name;

    @ManyToMany(mappedBy="roles")//mappedby Indicates it's the owned side of a m2m
    //"roles" name of the table to map from
    private List<User> users;
    //Create a list of Users that can be associated to the Roles
}
